headersOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\santi\\OneDrive\\Documents\\SLPL\\taneu\\frontend"
publishOrigin = "config"
commandOrigin = "ui"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]